name: Cleanup Infrastructure

on:
  workflow_call:
    inputs:
      terraform_version:
        description: 'The version of Terraform to use'
        required: false
        default: '1.9.4'
        type: string
      terraform_directory:
        description: 'The directory where Terraform configuration files are located'
        required: true
        type: string
      terraform_workspace:
        description: 'The Terraform workspace to use'
        required: true
        type: string
      tfvars_file:
        description: 'The path to the tfvars file'
        required: true
        type: string
      aws_region:
        description: 'The AWS region to use'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ inputs.terraform_directory }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}

      - name: Select Terraform Workspace
        run: |
          terraform workspace select -or-create=true ${{ inputs.terraform_workspace }}
        working-directory: ${{ inputs.terraform_directory }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}

      - name: Terraform Destroy
        run: terraform destroy -lock=false -auto-approve -var-file=${{ inputs.tfvars_file }}
        working-directory: ${{ inputs.terraform_directory }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}
